services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: financial-api-db
    ports:
      - "5432:5432"
    env_file: ".env.example"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations
    networks:
      - financial-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: financial-api-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.example
    networks:
      - financial-network

volumes:
  postgres_data:

networks:
  financial-network: